#pragma once
#include <iostream>
#include <string>
#include <vector>

// Label names
const std::vector<std::string> LabelString {
	"PERSON",
		"BICYCLE",
		"CAR",
		"MOTORBIKE",
		"AEROPLANE",
		"BUS",
		"TRAIN",
		"TRUCK",
		"BOAT",
		"TRAFFIC_LIGHT",
		"FIRE_HYDRANT",
		"STOP_SIGN",
		"PARKING_METER",
		"BENCH",
		"BIRD",
		"CAT",
		"DOG",
		"HORSE",
		"SHEEP",
		"COW",
		"ELEPHANT",
		"BEAR",
		"ZEBRA",
		"GIRAFFE",
		"BACKPACK",
		"UMBRELLA",
		"HANDBAG",
		"TIE",
		"SUITCASE",
		"FRISBEE",
		"SKIS",
		"SNOWBOARD",
		"SPORTS_BALL",
		"KITE",
		"BASEBALL_BAT",
		"BASEBALL_GLOVE",
		"SKATEBOARD",
		"SURFBOARD",
		"TENNIS_RACKET",
		"BOTTLE",
		"WINE_GLASS",
		"CUP",
		"FORK",
		"KNIFE",
		"SPOON",
		"BOWL",
		"BANANA",
		"APPLE",
		"SANDWICH",
		"ORANGE",
		"BROCCOLI",
		"CARROT",
		"HOT_DOG",
		"PIZZA",
		"DONUT",
		"CAKE",
		"CHAIR",
		"SOFA",
		"POTTEDPLANT",
		"BED",
		"DININGTABLE",
		"TOILET",
		"TVMONITOR",
		"LAPTOP",
		"MOUSE",
		"REMOTE",
		"KEYBOARD",
		"CELL_PHONE",
		"MICROWAVE",
		"OVEN",
		"TOASTER",
		"SINK",
		"REFRIGERATOR",
		"BOOK",
		"CLOCK",
		"VASE",
		"SCISSORS",
		"TEDDY_BEAR",
		"HAIR_DRIER",
		"TOOTHBRUSH",
};
// https://gist.github.com/nicobonik/a1f84a93dcc56b00dd1f0d1d310a256a
const std::vector<cv::Scalar> Colors{
	cv::Scalar(0, 255, 0),
	cv::Scalar(0, 0, 255),
	cv::Scalar(255, 0, 0),
	cv::Scalar(12, 21, 140),
	cv::Scalar(255, 0, 255),
	cv::Scalar(255, 51, 51),
	cv::Scalar(255, 255, 0),
	cv::Scalar(0, 255,255),
	cv::Scalar(0, 102, 51),
	cv::Scalar(0, 128, 255),
	cv::Scalar(255, 255, 255),
	cv::Scalar(0, 0, 0),
	cv::Scalar(96, 96, 96),
	cv::Scalar(204, 204, 255),
	cv::Scalar(204, 255, 255),
	cv::Scalar(204, 255, 204),
	cv::Scalar(255, 255, 204),
	cv::Scalar(255, 204, 204),
	cv::Scalar(229, 204, 255),

};

